connection: &connection
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  pool:     5

authentication: &authentication
  username: USERNAME
  password: PASSWORD

development:
  <<: *connection
  # <<: *authentication
  database: oneday_development

test:
  <<: *connection
  # <<: *authentication
  database: oneday_test

production:
  <<: *connection
  <<: *authentication
  database: oneday_production
